apiVersion: v1
kind: Secret
metadata:
  name: manura-discord-kube-api-secret
  annotations:
    kubernetes.io/service-account.name: manura-discord-service-account
type: kubernetes.io/service-account-token
