apiVersion: v1
kind: Secret
metadata:
  name: operator-oauth
type: Opaque
data:
  clientId: ref+sops://sops.encrypted.yaml#/oauthClientId
  clientSecret: ref+sops://sops.encrypted.yaml#/oauthClientSecret
