apiVersion: v1
kind: ConfigMap
metadata:
  name: pokemanura-api-postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: {{ .Values.postgres.database }}
  POSTGRES_USER: {{ .Values.postgres.user }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password }}
  PGDATA: /var/lib/postgresql/data/pgdata
