apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pokemanura-api-postgres-pvc
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
