apiVersion: v1
kind: Service
metadata:
  name: pokemanura-api-postgres
  labels:
    app: postgres
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
